# Water mass analysis parameters file for MPAS CORE-II G-cases
# 
#
# ---------- Run details --------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------------------
run:
  simName: 20210421_sim7_CORE
  prefix: mpaso.hist.am.timeSeriesStatsMonthly
  meshPath: /global/cfs/cdirs/e3sm/inputdata/ocn/mpas-o
  maskPath: /pscratch/sd/b/bmoorema/maskfiles
  meshName:
    LR: EC30to60E2r2
    HR: oRRS18to6v3
  resultsPath:
    LR: /pscratch/sd/b/bmoorema/run_001_062
    HR: [/global/cfs/cdirs/m4259/lvroekel, [run_001_010, run_011_020, run_051_060]]
  meshFile:
    LR: ocean.EC30to60E2r2.210210.nc
    HR: oRRS18to6v3.171116.nc
  maskFile:
    LR: EC30to60E2r2_transformationbudgetmasks20240724.nc
    HR: oRRS18to6v3_transformationbudgetmasks20240724.nc

# ---------- Flux names ---------------------------------------------------------------------------------------
# -------------------------------------------------------------------------------------------------------------
fluxes:
  temperature         : activeTracers_temperature         # Potential temperature ----------- [deg C]
  salinity            : activeTracers_salinity            # Salinity ------------------------ [PSU]
  totalHeatFlux:
    shortWave         : shortWaveHeatFlux                 # Short wave radiation flux ------- [W m-2]
    longWaveUp        : longWaveHeatFluxUp                # Upward long wave heat flux ------ [W m-2]
    longWaveDown      : longWaveHeatFluxDown              # Downward long wave heat flux ---- [W m-2]
    latent            : latentHeatFlux                    # Latent heat flux ---------------- [W m-2]
    sensible          : sensibleHeatFlux                  # Sensible heat flux -------------- [W m-2]
    seaIceHeat        : seaIceHeatFlux                    # Sea ice heat flux --------------- [W m-2]
  totalFreshFlux:
    evaporation       : evaporationFlux                   # Evaporation flux ---------------- [kg m-2 s-1]
    rain              : rainFlux                          # FW flux from rain --------------- [kg m-2 s-1]
    snow              : snowFlux                          # FW flux from snow --------------- [kg m-2 s-1]
    riverRunoff       : riverRunoffFlux                   # FW flux from river runoff ------- [kg m-2 s-1]
    iceRunoff         : iceRunoffFlux                     # FW flux from ice runoff --------- [kg m-2 s-1]
    seaIceFW          : seaIceFreshWaterFlux              # FW flux from sea ice ------------ [kg m-2 s-1]
  totalSaltFlux:
    seaIceSalinity    : seaIceSalinityFlux                # Salinity flux from sea ice ------ [kg SALT m-2 s-1]
  totalSalinityFlux:
    salinityRestoring : salinitySurfaceRestoringTendency  # Salinity restoring tendency ----- [PSU m s-1]